version: '3'

services:
  blog-rest:
    build:
      context: .
      dockerfile: ./cmd/blog/rest/Dockerfile
    ports:
      - "19000:8080"
    environment:
      - CANDI_API_BASE_URL=https://api.helochat.id
      - CANDI_BASIC_AUTH=Y2wtMHgyOTQ0OWQwMDpFVkw2Sk5ST1J2aVdncmhjeFU1UXZR
      - AWS_SES_REGION=us-east-1
      - AWS_SES_CODE_TTL_DEFAULT=30m
